name: gha-checkout
description: Composite action to checkout current repository, initialise private submoduels and checkout private actions repository
author: Doktor.se

inputs:
  token:
    description: Github PAT with access to repo, submodules and actions
    required: false

  fetch-depth:
    description: Number of commits to fetch, this applies to code and submodule, not actions. 0 indicates all history for all branches and tags.
    default: 1
    required: false

  submodules:
    description: Whether to checkout submodules `true` to checkout submodules or `recursive` to recursively checkout submodules.
    default: true
    required: false

  actions:
    description: Repository name for private actions, set to 'false' to skip
    default: composite-actions
    required: false

  actions-ref:
    description: Git reference to checkout for private actions
    required: false
    default: main

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ inputs.token }}
        fetch-depth: ${{ inputs.fetch-depth }}
        submodules: ${{ inputs.submodules }}

    - name: Checkout private actions
      if: ${{ inputs.actions != '' && inputs.actions != 'false' }}
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository_owner }}/${{ inputs.actions }}
        ref: ${{ inputs.actions-ref }}
        path: .github/${{ inputs.actions }}
        token: ${{ inputs.token }}
        persist-credentials: false

