name: gha-checkout
description: Composite action to checkout current repository, initialise private submoduels and checkout private actions repository
author: Doktor.se

inputs:
  token:
    description: Github PAT with access to repo, submodules and actions
    required: false

  fetch-depth:
    description: Number of commits to fetch, this applies to code and submodule, not actions. 0 indicates all history for all branches and tags.
    default: 1
    required: false

  private_actions:
    description: Repository name for private actions
    required: false
    default: composite-actions

  actions_ref:
    description: Git reference to checkout for private actions
    required: false
    default: main

  submodules:
    description: Whether to checkout submodules `true` to checkout submodules or `recursive` to recursively checkout submodules.
    default: true
    required: false

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ input.token }}
        fetch-depth: ${{ input.fetch-depth }}
        submodules: ${{ input.submodules }}

    - name: Checkout private actions
      if: ${{ inputs.actions_key != '' }}
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository_owner }}/${{ inputs.private_actions }}
        ref: ${{ inputs.actions_ref }}
        path: .github/${{ inputs.private_actions }}
        token: ${{ input.token }}
        persist-credentials: false

